spring:
  application:
    name: ProofReader

proofreader:
  installationId: 12345
  clientId: AbCd123
  sourceRepo:
    owner: PaperMC
    name: Paper
  targetRepo:
    owner: PaperMC
    name: ProofReading
  privateKey: |
    -----BEGIN RSA PRIVATE KEY-----
